### ISSUE TITLE
zones with vrrp vnics broken since commit for OS-2994 and OS-4582

### ISSUE THREAD

**Issue by stevenwilliamson** [joyent/smartos-live#504]
Zones that have a VRRP NIC fail to start on releases after the above commits were merged. The zone fails to start and the physical net SMF services are left in maint:

```

svc:/network/physical:default (physical network interfaces)
 State: maintenance since Wed Oct 28 12:51:28 2015
Reason: Start method failed repeatedly, last exited with status 2.
   See: http://illumos.org/msg/SMF-8000-KS
   See: man -M /usr/share/man -s 1M ifconfig
   See: /var/svc/log/network-physical:default.log
Impact: 6 dependent services are not running:
        svc:/network/routing-setup:default
        svc:/milestone/network:default
        svc:/network/shares/group:default
        svc:/network/shares/group:zfs
        svc:/network/iptun:default
        svc:/network/ssh:default

svc:/network/physical:nwam (physical network interface autoconfiguration)
 State: disabled since Wed Oct 28 12:51:25 2015
Reason: Disabled by an administrator.
   See: http://illumos.org/msg/SMF-8000-05
   See: man -M /usr/share/man -s 1M nwamd
   See: http://opensolaris.org/os/projects/nwam/
   See: http://opensolaris.org/os/projects/nwam/phase0/
Impact: 6 dependent services are not running:
        svc:/network/routing-setup:default
        svc:/milestone/network:default
        svc:/network/shares/group:default
        svc:/network/shares/group:zfs
        svc:/network/iptun:default
        svc:/network/ssh:default
```

The problem was introduced in commit 837b13405c6e871699999565a02e33ac0a8ba075

Calls to `ifconfig plumb` were replaced to a function call `plumbif`

The function plumbif always appends `up` for an interface plumb. When we don't configure an address and bring the interface up with ifconfig such as with a VRRP vnic this leads the below ifconfig error, and the script exits.

```
ifconfig: setifflags: SIOCSLIFFLAGS: net2: Invalid argument
[ Nov  3 15:59:54 Method "start" exited with status 1. ]
```

As can be seen below, before this commit for VRRP vnic's the ifconfig was called with plumb with out the additional up.

```
 /sbin/ifconfig ${iface} plumb
            # vrrp interfaces can't be brought up with ifconfig: vrrpadm
            # handles that instead
            if [[ "${addrtype}" =~ "^vrrp" ]]; then
                /sbin/ifconfig ${iface} inet `cat /etc/hostname.${iface} \
                    | sed -e 's/ up//'`
            else
                /sbin/ifconfig ${iface} inet `cat /etc/hostname.${iface}` up
            fi
```

Looking at the processes running when the method script is run we can see the commands clearly run:

```
  2   7674         exec_common:exec-success   /usr/bin/ksh93 /lib/svc/method/net-physical
  2   7674         exec_common:exec-success   /usr/bin/ksh93 /lib/svc/method/net-physical
  3   7674         exec_common:exec-success   /sbin/zonename
  0   7674         exec_common:exec-success   /sbin/zonename -t
  0   7674         exec_common:exec-success   /usr/sbin/dladm show-vnic -p -o link,macaddrtype
  1   7674         exec_common:exec-success   /sbin/ifconfig net1 inet plumb up
  0   7674         exec_common:exec-success   /sbin/ifconfig net1 inet 192.168.224.251/24 up up
  0   7674         exec_common:exec-success   /sbin/ifconfig net2 inet plumb up
```

Additionally it looks like there is another lurking bug that has no direct affect in that up is appended twice for some of the calls.

**Comment by melloc** [comment]
I've filed [OS-4933](https://smartos.org/bugview/OS-4933) for this issue. I have a fix for this, but haven't done much testing for it yet. I'll update this issue once it's been tested and pushed.

**Comment by stevenwilliamson** [comment]
@melloc any update on this, anything I can help test.

**Comment by melloc** [comment]
I haven't had a chance to test out VRRP NICs, but I've been using the following build with the changes I made while doing some other work, so they work with standard NICs, and should fix the issue with VRRP:

https://us-east.manta.joyent.com/cody.mello/public/builds/OS-4993/platform-20151202T171655Z.tgz
https://us-east.manta.joyent.com/cody.mello/public/builds/OS-4993/platform-20151202T171655Z.usb.bz2
https://us-east.manta.joyent.com/cody.mello/public/builds/OS-4993/platform-20151202T171655Z.iso

Let me know how these work out for you. Any testing is appreciated. :)

**Comment by stevenwilliamson** [comment]
@melloc no such luck im afraid it still fails.

However to make it work is a simple patch.

```
--- net-physical	2015-12-11 17:19:26.346973948 +0000
+++ /lib/svc/method/net-physical	2015-12-11 17:17:11.332442000 +0000
@@ -449,7 +449,7 @@
     if [[ -z ${plumbedifs[${iface},${inet}]} ]]; then
         plumbedifs[${iface},${inet}]="true"
         /sbin/ifconfig ${iface} ${inet} plumb
-        if [[ ${addrtype} != "^vrrp" ]]; then
+        if [[ ! ${addrtype} =~ "^vrrp" ]]; then
             /sbin/ifconfig ${iface} ${inet} up
         fi
     fi
```

The issue is that addrtype is actually set to "vrrp," due the read call that populates the variable splitting on ":" it picks some junk from the /etc/hostname.iface file notably a comma.

In ksh it seems != is a pattern match not a regexp so the above fails and we try to setup the VRRP nic. So changing it to a regexp and then negating it works.

Testing with this patch my test zone correctly brings up all the nics.

**Comment by melloc** [comment]
Thanks for testing! I've also updated line 787. I'll put these changes in the next release.

**Comment by melloc** [comment]
Fixed by OS-4933 in 114d19c.
